display: "&8&lDEFAULT"
requires-tier: none # Set to 'none' to always allow application
crystal-craftable: false
crystal-name: "&8Default Upgrade Crystal"
crystal-recipe:
  - air
  - leather
  - air

  - leather
  - leather_chestplate
  - leather

  - air
  - leather
  - air
crystal-lore:
  - "&8Drop this onto an armor piece"
  - "&8to set its tier to:"
  - "&8&lDEFAULT"
properties:
  helmet:
    armor: 1
    toughness: 0
    knockback-resistance: 0
    speed-percentage: 0
    attack-speed-percentage: 0
    attack-damage-percentage: 0
    attack-knockback-percentage: 0
  chestplate:
    armor: 3
    toughness: 0
    knockback-resistance: 0
    speed-percentage: 0
    attack-speed-percentage: 0
    attack-damage-percentage: 0
    attack-knockback-percentage: 0
  elytra:
    armor: 0
    toughness: 0
    knockback-resistance: 0
    speed-percentage: 0
    attack-speed-percentage: 0
    attack-damage-percentage: 0
    attack-knockback-percentage: 0
  leggings:
    armor: 2
    toughness: 0
    knockback-resistance: 0
    speed-percentage: 0
    attack-speed-percentage: 0
    attack-damage-percentage: 0
    attack-knockback-percentage: 0
  boots:
    armor: 1
    toughness: 0
    knockback-resistance: 0
    speed-percentage: 0
    attack-speed-percentage: 0
    attack-damage-percentage: 0
    attack-knockback-percentage: 0